### ISSUE TITLE
Stopping slider from moving

### ISSUE THREAD

**Issue by xavierpuigf** [ladrower/jquery-ui-intervals#1]
Is there a way to stop the slider of one interval from moving when a certain event occurs? I would need to have something as this http://stackoverflow.com/questions/12429773/stopping-the-jquery-ui-slider-from-moving-past-a-given-value but I am not sure if this is possible in jquery-ui-intervals.

**Comment by ladrower** [comment]
Added `setOnBeforeHandleSlideCallback` method in callback of which returned `false` value will stop the slider from moving.
