### ISSUE TITLE
Get values

### ISSUE THREAD

**Issue by uweoswald** [ladrower/jquery-ui-intervals#3]
Hi,
please forgive me not hitting the right page probably but I'm not very familar with git. All what I want to know is how can I access the values from "outside" the constructor and callback. For example per Jquery. All what I can see is the "first" addPeriod but anaything else which has been added dynamically ist not accessible. 

Aehm, the slider is the best what I have found so far is fits perfect in my project. Hope you can help me.

Thank you in advance for your help.

Regards,
Uwe (from cold Germany :-))

**Comment by ladrower** [comment]
Hello,
the intervals instance has public method `getPeriods()` that returns an array of period objects each of which has `getAbscissas()` method to get the actual values for that particular period.

So, to get an array of all the actual values you may use the following:

``` javascript
// Create an instance of Intervals
var intervals = new Intervals("#slider");
//...
// And somewhere later in the code
var values = intervals.getPeriods().map(function (period) {
    return period.getAbscissas();
});

// values will contain an array of arrays. Something like [ [10, 20], [50, 70] ]
```

Or if you would like to get an array of objects with properties `a`, `b` corresponding to the beginning and the end of the period:

``` javascript
var values = intervals.getPeriods().map(function (period) {
    var x = period.getAbscissas();
    return {
        a: x[0],
        b: x[1]
    };
});

// values will contain an array of objects. Something like [ {a: 10, b: 20}, {a: 50, b: 70} ]
```
